### PR TITLE
Inc version

### PR DESCRIPTION
**Pull request by joachimprinzbach**

### CODE REVIEW

**Comment by joachimprinzbach** [comment]
Welcome to Baloise ChatOps based GitOps Bot.<br><br>If you want to enable preview environments for this PullRequest, comment with `/preview`.<br>If you want to disable the preview environment for this PR, comment with `/undeploy`.<br>If you need help or want to see the docs, comment with `/help`.<br><br>At the moment, preview environments do not get redeployed automatically. Simply rewrite `/preview` or contribute the feature.

**Comment by joachimprinzbach** [comment]
Need help? Find the docs, examples and a F.A.Q.: [Baloise Incubator: GitOps Cli](https://baloise-incubator.github.io/gitopscli/)

**Comment by joachimprinzbach** [comment]
New Preview Environment for gitops-example-static and branch master created successfully. Access it here: 
https://example-fc613b4d.apps.origin.baloise.dev

**Comment by incubator-tekton** [comment]
The version e2db4181dde14a46eb0079e5e026aa694db01768 has already been deployed. Nothing to do here.

**Pull request closed without merging**
