### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by niiku**

### CODE REVIEW

**Comment by incubator-tekton** [comment]
Welcome to Baloise ChatOps based GitOps Bot.<br><br>If you want to enable preview environments for this PullRequest, comment with `/preview`.<br>If you want to disable the preview environment for this PR, comment with `/undeploy`.<br>If you need help or want to see the docs, comment with `/help`.<br><br>At the moment, preview environments do not get redeployed automatically. Simply rewrite `/preview` or contribute the feature.

**Comment by niiku** [comment]
Welcome to Baloise ChatOps based GitOps Bot.

If you want to enable preview environments for this PullRequest, comment with /preview.
If you want to disable the preview environment for this PR, comment with /undeploy.
If you need help or want to see the docs, comment with /help.

At the moment, preview environments do not get redeployed automatically. Simply rewrite /preview or contribute the feature.

**Comment by incubator-tekton** [comment]
New preview environment created for version `52f60e4c43b2fafc84262c32178e77e435a21119`. Access it here: https://gitops-nginx-demo-a5bf711c.apps.okd.baloise.dev

**Pull request closed without merging**
