### PR TITLE
Inc version

### PR DESCRIPTION
**Pull request by joachimprinzbach**

### CODE REVIEW

**Comment by incubator-tekton** [comment]
Welcome to Baloise ChatOps based GitOps Bot.<br><br>If you want to enable preview environments for this PullRequest, comment with `/preview`.<br>If you want to disable the preview environment for this PR, comment with `/undeploy`.<br>If you need help or want to see the docs, comment with `/help`.<br><br>At the moment, preview environments do not get redeployed automatically. Simply rewrite `/preview` or contribute the feature.

**Comment by incubator-tekton** [comment]
New Preview Environment for gitops-example-static and branch master created successfully. Access it here: 
https://example-fc613b4d.apps.origin.baloise.dev

**Comment by joachimprinzbach** [comment]
ad

**Comment by joachimprinzbach** [comment]
a

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
a

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
a

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
a

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
sad

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
asd

**Comment by incubator-tekton** [comment]
New Preview Environment for gitops-example-static and branch feat/version created successfully. Access it here: 
https://example-c60f55d3.apps.origin.baloise.dev

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
as

**Comment by joachimprinzbach** [comment]
as

**Comment by joachimprinzbach** [comment]
as

**Comment by joachimprinzbach** [comment]
asssss

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
asdsad

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
a

**Comment by joachimprinzbach** [comment]
asd

**Comment by joachimprinzbach** [comment]
a

**Comment by incubator-tekton** [comment]
The version 667aae21b1ddae68bae376b4686e65474b482512 has already been deployed. Nothing to do here.

**Comment by incubator-tekton** [comment]
The version 667aae21b1ddae68bae376b4686e65474b482512 has already been deployed. Nothing to do here.

**Pull request closed without merging**
