### PR TITLE
Fix OKD link / Change wording

### PR DESCRIPTION
**Pull request by niiku**

### CODE REVIEW

**Comment by incubator-tekton** [comment]
Welcome to Baloise ChatOps based GitOps Bot.<br><br>If you want to enable preview environments for this PullRequest, comment with `/preview`.<br>If you want to disable the preview environment for this PR, comment with `/undeploy`.<br>If you need help or want to see the docs, comment with `/help`.<br><br>At the moment, preview environments do not get redeployed automatically. Simply rewrite `/preview` or contribute the feature.

**Comment by incubator-tekton** [comment]
New Preview Environment for gitops-nginx-demo and branch minor-changes created successfully. Access it here: 
https://gitops-nginx-demo-e22ca709.apps.origin.baloise.dev

**Comment by joachimprinzbach** [comment]
GitOps Cli or CLI?

**Comment by christiansiegel** [comment]
GitOps CLI

**Comment by incubator-tekton** [comment]
Preview Environment for gitops-nginx-demo and branch minor-changes updated successfully. Access it here: 
https://gitops-nginx-demo-e22ca709.apps.origin.baloise.dev

**Pull request merged**
